apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: fastapi-backend
          image: techfreaksyed/product-app:backend # REPLACE THIS
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          # Handling the .env file from compose:
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend # This name is critical; frontend uses it to talk to backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000 # The port inside the cluster
      targetPort: 8000 # The port the container listens on
  type: LoadBalancer # <-- Changed from ClusterIP
  loadBalancerClass: tailscale # <-- Added Tailscale loadBalancerClass
