apiVersion: v1

kind: ConfigMap

metadata:
  name: backend-config

data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 1234
  POSTGRES_DB: product_db
  POSTGRES_SERVER: 192.168.1.103
  POSTGRES_PORT: 5432
