apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    # This tells Tailscale to create a magic link for this app
    tailscale.com/expose: "true"
spec:
  # This tells Kubernetes to use the Tailscale driver instead of Nginx
  ingressClassName: tailscale 
  rules:
  - host: home.tail2b1f38.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crud-app-service  # <--- Make sure this matches your Service name!
            port:
              number: 80            # <--- Make sure this matches your Service port!