apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    # This tells the Tailscale Operator to create a machine in your Tailnet
    tailscale.com/expose: "true"
spec:
  ingressClassName: tailscale
  rules:
  - host: home.tail2b1f38.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend  # <--- Matches the name in frontend.yml
            port:
              number: 80    # <--- Matches the port in frontend.yml